global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'autofixer'
    static_configs:
      - targets: ['autofixer:3000']
    metrics_path: '/metrics'
    scrape_interval: 30s

  - job_name: 'sonarqube'
    static_configs:
      - targets: ['sonarqube:9000']
    metrics_path: '/metrics'
    scrape_interval: 60s
