version: 2
updates:
  # Enable version updates for npm (JavaScript/TypeScript)
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "06:00"
      timezone: "UTC"
    open-pull-requests-limit: 10
    allow:
      - dependency-type: "direct"
    groups:
      expo:
        patterns:
          - "expo*"
          - "@expo/*"
      react-native:
        patterns:
          - "react-native*"
          - "@react-native*/*"
      livekit:
        patterns:
          - "livekit*"
          - "@livekit/*"
      linting:
        patterns:
          - "eslint*"
          - "@typescript-eslint/*"
          - "prettier"
      misc-patches:
        patterns:
          - "*"
        exclude-patterns:
          - "expo*"
          - "@expo/*"
          - "react-native*"
          - "@react-native*/*"
          - "livekit*"
          - "@livekit/*"
          - "eslint*"
          - "@typescript-eslint/*"
          - "prettier"

  # Enable version updates for Cargo (Rust/Tauri)
  - package-ecosystem: "cargo"
    directory: "/src-tauri"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 3
    commit-message:
      prefix: "deps"
      include: "scope"
    labels:
      - "dependencies"
      - "rust"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "06:00"
      timezone: "UTC"
