# 🤖 Distributed Build Worker Configuration
# This file configures how your GitHub Actions workers distribute builds

# Worker Pool Settings
worker_pool:
  # Default number of parallel workers
  default_count: 4
  # Maximum workers to use (prevents resource overload)  
  max_count: 8
  # Worker timeout settings (minutes)
  timeouts:
    web_build: 15
    mobile_build: 25
    test_suite: 40
    coordination: 5

# Build Matrix Configuration
build_matrix:
  # Web builds - different optimization levels and targets
  web:
    - config: development
      optimize: false
      bundle: modern
      description: "Fast development build for testing"
    - config: production  
      optimize: true
      bundle: modern
      description: "Optimized modern build for deployment"
    - config: production
      optimize: true
      bundle: legacy
      description: "Optimized legacy build for older browsers"
      
  # Mobile builds - platform and variant combinations
  mobile:
    - platform: ios
      variant: development
      architecture: x64
      description: "iOS development build"
    - platform: ios
      variant: production
      architecture: x64
      description: "iOS production build"
    - platform: android
      variant: development
      architecture: x64
      description: "Android development build"
    - platform: android
      variant: production
      architecture: x64
      description: "Android production build"

  # Test suites - parallel test execution
  tests:
    - suite: unit
      pattern: "**/*.test.ts"
      timeout: 10
      description: "Unit tests for individual components"
    - suite: integration
      pattern: "**/*.integration.test.ts"
      timeout: 20
      description: "Integration tests for component interactions"
    - suite: stress
      pattern: "**/*.stress.test.ts"
      timeout: 30
      description: "Performance and stress tests"
    - suite: e2e
      pattern: "**/*.e2e.test.ts"
      timeout: 40
      description: "End-to-end user flow tests"

# Resource Allocation
resources:
  # Concurrent job limits to prevent GitHub Actions quota issues
  max_parallel:
    web_builds: 3      # 3 web builds can run simultaneously
    mobile_builds: 2   # 2 mobile builds can run simultaneously  
    test_suites: 4     # 4 test suites can run simultaneously
    
  # Node.js and dependency settings
  node:
    version: "20"
    cache_strategy: "yarn"
    install_args: "--frozen-lockfile --prefer-offline"
    
  # Artifact retention (days)
  retention:
    build_artifacts: 7
    test_results: 30

# Performance Optimizations
optimizations:
  # Enable aggressive caching
  cache_enabled: true
  # Use dependency caching across jobs
  dependency_cache: true  
  # Upload artifacts in parallel
  parallel_uploads: true
  # Skip builds if no relevant changes detected
  smart_builds: true

# Trigger Configuration
triggers:
  # Branches that should use worker builds
  branches:
    - main
    - dev
    - "feature/*"
    - "release/*"
  # File patterns that should trigger worker builds
  paths:
    - "sources/**"
    - "*.js"
    - "*.ts"
    - "*.tsx"
    - "package.json"
    - "yarn.lock"
    - "app.config.js"

# Notification Settings
notifications:
  # Success/failure reporting
  slack_webhook: null  # Set to your Slack webhook URL if desired
  email_on_failure: false
  github_status_checks: true
  
# Advanced Settings
advanced:
  # Cancel previous runs when new commits pushed
  cancel_in_progress: true
  # Fail fast if critical jobs fail
  fail_fast: false
  # Enable debug logging
  debug_mode: false